{{ if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "k8s-pause.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "k8s-pause.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "k8s-pause.chart" . }}
    {{- range $key, $value := .Values.podMonitor.additionalLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- if .Values.podMonitor.namespace }}
  namespace: {{ .Values.podMonitor.namespace }}
  {{- end }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
spec:
  podMetricsEndpoints:
  - port: metrics
    path: {{ .Values.metricsPath }}
    interval: {{ .Values.podMonitor.interval }}
    scrapeTimeout: {{ .Values.podMonitor.scrapeTimeout }}
    {{- if .Values.podMonitor.metricRelabelings }}
    metricRelabelings: {{ toYaml .Values.podMonitor.metricRelabelings | nindent 4 }}
    {{- end }}

  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "k8s-pause.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.podMonitor.targetLabels }}
  targetLabels:
{{- range .Values.podMonitor.targetLabels }}
    - {{ . }}
{{- end }}
{{- end }}
  sampleLimit: {{ .Values.podMonitor.sampleLimit }}
{{- end }}
